In [1]:
import numpy as np

## Data Types && Attributes

In [9]:
a1 = np.array([1,2,3])
a1.shape

(3,)

In [4]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,2,3],
               [4,5,6],
              [7,8,9]])
a2
a2.shape

(3, 3)

In [23]:
a3 = np.array([[[1,2,3],
                 [4,5,6],
                [7,8,9]],
                
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])
a3.shape

(2, 3, 3)

In [25]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [26]:
a1.size


3

In [27]:
a1.dtype

dtype('int64')

In [28]:
type(a1)

numpy.ndarray

In [32]:
# creating dataframe from numpy array.
import pandas as pd

df = pd.DataFrame({'First':a2[0], 'Second':a2[1]})
df

First  Second
0      1       4
1      2       5
2      3       6

## Creating arrays

In [44]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_number = np.arange(2,10,2)
range_number

array([2, 4, 6, 8])

In [53]:
random_array = np.random.randint(2,10, size = (2,3))
random_array

array([[9, 4, 7],
       [4, 3, 7]])

In [63]:
np.random.random((4,5))

array([[0.06460496, 0.50416296, 0.4490711 , 0.65662551, 0.8443012 ],
       [0.92341693, 0.06207803, 0.14171926, 0.01581231, 0.86173832],
       [0.14577975, 0.79913147, 0.53432347, 0.82495953, 0.10200434],
       [0.03237305, 0.92784506, 0.80643132, 0.73425443, 0.30441415]])

In [64]:
np.random.rand(2,3)

array([[0.26382345, 0.73083214, 0.68312156],
       [0.93076342, 0.02262419, 0.12038857]])

In [157]:
np.random.seed(0)
random_array_1 = np.random.randint(10, size=(4,5))
random_array_1
#np.unique(random_array_1)


array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

## Viewing arrays and matrices

In [158]:
a1

array([1, 2, 3])

In [159]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [161]:
        a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
a2[:2, :2]

array([[1, 2],
       [4, 5]])

In [167]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 2, 3, 3, 4],
         [1, 6, 2, 5, 4],
         [9, 1, 5, 9, 4],
         [5, 7, 4, 4, 2]],

        [[2, 1, 3, 0, 1],
         [9, 1, 6, 9, 8],
         [6, 3, 0, 7, 3],
         [2, 5, 9, 7, 3]],

        [[4, 7, 6, 7, 3],
         [6, 9, 3, 7, 1],
         [3, 7, 8, 8, 4],
         [5, 3, 6, 9, 6]]],


       [[[2, 9, 3, 5, 7],
         [9, 0, 7, 1, 2],
         [5, 0, 5, 8, 9],
         [8, 2, 5, 3, 1]],

        [[7, 3, 8, 5, 5],
         [1, 9, 7, 2, 1],
         [0, 1, 0, 1, 1],
         [6, 8, 8, 3, 2]],

        [[0, 7, 4, 6, 0],
         [5, 3, 3, 9, 4],
         [9, 0, 6, 5, 3],
         [0, 0, 1, 2, 0]]]])

In [165]:
a4.ndim

4

## Manipulating and comparing arrays

### Arithmatic

In [169]:
a1


array([1, 2, 3])

In [170]:
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [171]:
a2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
one = np.ones((3,3))

In [173]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [174]:
a2+one

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [175]:
a2*one

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [176]:
one/a2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [177]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [179]:
np.add(a1,one)

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [181]:
np.square(a1)

array([1, 4, 9])

## Aggregation

In [183]:
a1

array([1, 2, 3])

In [184]:
sum(a1)

6

In [185]:
np.sum(a1)

6

In [186]:
np.sum(a2)

45

In [187]:
np.sum(a3)

171

In [188]:
%timeit sum(a3)  ##%timeit is a magic function.

4.33 µs ± 91.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [189]:
%timeit np.sum(a3)

7.15 µs ± 41.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [190]:
np.mean(a1)

2.0

In [191]:
np.max(a1)

3

In [192]:
np.min(a2)

1

In [193]:
np.std(a1)

0.816496580927726

In [194]:
np.var(a1)

0.6666666666666666

In [195]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
a2.shape

(3, 3)

In [200]:
a2 * a3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [201]:
a = a2*a3

In [203]:
a.shape

(2, 3, 3)

In [204]:
a.reshape(6,3)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [205]:
# Transpose
a

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [208]:
a.T

array([[[  1,  10],
        [ 16,  52],
        [ 49, 112]],

       [[  4,  22],
        [ 25,  70],
        [ 64, 136]],

       [[  9,  36],
        [ 36,  90],
        [ 81, 162]]])

## Dot Product

In [209]:
mat1 = np.random.randint(10, size = (4,5))
mat2 = np.random.randint(10, size = (4,5))

In [210]:
mat1

array([[2, 2, 9, 6, 7],
       [8, 9, 8, 2, 4],
       [7, 7, 5, 7, 2],
       [4, 1, 1, 1, 7]])

In [211]:
mat2

array([[9, 0, 9, 0, 2],
       [1, 4, 6, 0, 6],
       [6, 2, 8, 6, 6],
       [5, 2, 5, 0, 3]])

In [212]:
mat1 * mat2

array([[18,  0, 81,  0, 14],
       [ 8, 36, 48,  0, 24],
       [42, 14, 40, 42, 12],
       [20,  2,  5,  0, 21]])

In [216]:
mat2 = mat2.reshape(5,4)

In [219]:
mat = np.dot(mat1, mat2)
mat

array([[ 84, 127, 116,  81],
       [114,  89, 168,  92],
       [137,  89, 163,  93],
       [ 60,  48,  52,  34]])

In [220]:
mat.shape

(4, 4)

In [222]:
number_sales = np.random.randint(10, size=(4,4))
number_sales

array([[9, 9, 7, 0],
       [4, 1, 3, 5],
       [7, 6, 2, 7],
       [3, 4, 9, 7]])

In [240]:
df1 = pd.DataFrame(number_sales, index = ['Sunday','Monday','Tuesday','Wednesday'],columns = ['Milk', 'Biscuits','Noodles','Chocolate'])


In [232]:
prices = np.array([100,200,300,400])
prices

array([100, 200, 300, 400])

In [260]:
prices_1 = pd.DataFrame(prices.reshape(1,4), index=['Price'], columns=['Milk', 'Biscuits','Noodles','Chocolate'])

In [261]:
prices_1

Milk  Biscuits  Noodles  Chocolate
Price   100       200      300        400

In [235]:
number_sales

array([[9, 9, 7, 0],
       [4, 1, 3, 5],
       [7, 6, 2, 7],
       [3, 4, 9, 7]])

In [236]:
prices

array([100, 200, 300, 400])

In [238]:
total_sales = np.dot(number_sales, prices)

In [239]:
total_sales

array([4800, 3500, 5300, 6600])

In [241]:
df1

Milk  Biscuits  Noodles  Chocolate
Sunday        9         9        7          0
Monday        4         1        3          5
Tuesday       7         6        2          7
Wednesday     3         4        9          7

In [258]:
prices_1 = total_sales
prices_1

array([4800, 3500, 5300, 6600])

In [256]:

df2 = pd.DataFrame(np.dot(number_sales.T,prices.T))

In [262]:
prices = total_sales

In [263]:
prices

array([4800, 3500, 5300, 6600])

In [264]:
prices_1 = pd.DataFrame(prices.reshape(1,4), index=['Price'], columns=['Milk', 'Biscuits','Noodles','Chocolate'])

In [265]:
prices_1

Milk  Biscuits  Noodles  Chocolate
Price  4800      3500     5300       6600

In [267]:
df1

Milk  Biscuits  Noodles  Chocolate
Sunday        9         9        7          0
Monday        4         1        3          5
Tuesday       7         6        2          7
Wednesday     3         4        9          7

In [271]:
df1['Total'] = prices.T

In [272]:
df1

Milk  Biscuits  Noodles  Chocolate  Total
Sunday        9         9        7          0   4800
Monday        4         1        3          5   3500
Tuesday       7         6        2          7   5300
Wednesday     3         4        9          7   6600

## Comparision operators 

In [273]:
a1

array([1, 2, 3])

In [274]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [275]:
a1>a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [276]:
a2>a1

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [277]:
a1>2

array([False, False,  True])

In [278]:
a3>5

array([[[False, False, False],
        [False, False,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [279]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [280]:
random_array = np.random.randint(20, size = (5,4))

In [281]:
random_array

array([[ 0, 16, 17,  8],
       [19, 15, 16, 17],
       [10, 17,  3,  7],
       [ 9,  3,  7, 16],
       [ 2,  4,  4,  6]])

In [282]:
np.sort(random_array)

array([[ 0,  8, 16, 17],
       [15, 16, 17, 19],
       [ 3,  7, 10, 17],
       [ 3,  7,  9, 16],
       [ 2,  4,  4,  6]])

In [283]:
np.argsort(random_array)

array([[0, 3, 1, 2],
       [1, 2, 3, 0],
       [2, 3, 0, 1],
       [1, 2, 0, 3],
       [0, 1, 2, 3]])

In [284]:
a1.min()

1

In [285]:
a1.max()

3

In [286]:
np.min(a1)

1

In [287]:
np.argmin(a1)

0

In [288]:
np.argmax(a1)

2

In [289]:
random_array

array([[ 0, 16, 17,  8],
       [19, 15, 16, 17],
       [10, 17,  3,  7],
       [ 9,  3,  7, 16],
       [ 2,  4,  4,  6]])

In [290]:
np.argmax(random_array)

4

In [291]:
np.argmax(random_array, axis = 0)

array([1, 2, 0, 1])

In [292]:
np.argmax(random_array, axis = 1)

array([2, 0, 1, 3, 3])

<img src="corona.png"/>

In [294]:
from matplotlib.image import imread 
img = imread('corona.png')

In [296]:
img.dtype

dtype('float32')

In [297]:
type(img)

numpy.ndarray

In [298]:
img.shape

(565, 565, 4)

In [299]:
img.size

1276900

In [300]:
img.ndim

3